services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: plantid_discord_bot
    environment:
      - MIX_ENV=prod
      - PLANTNET_API_KEY=${PLANTNET_API_KEY}
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - LOGS_DISCORD_WEBHOOK_URL=${LOGS_DISCORD_WEBHOOK_URL}
    ports:
      - "4321:4321"
    volumes:
      - appdata:/plantid_discord_bot

volumes:
  appdata: